### PR TITLE
Oxid 459 compatibility with oxid 6

### PR DESCRIPTION
**Pull request by Skistims**
# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I updated the CHANGELOG.md

### CODE REVIEW

**Review by aaron-martin — APPROVED** [review]
The changes look good. I would have liked to test these in my test environment but there is something wrong with it right now and I don't want this to wait until I manage to fix it.

**Comment by augsteyer** [comment]
Waiting is good young Padawan, he may have messed it up completely. All
that stands between him and disaster is you. Go with the force.

**Review by aaron-martin — CHANGES_REQUESTED** [review]
Found issue in Oxid dash board. When shopgate plugin is active order details can not be viewed.

**Review by aaron-martin — APPROVED** [review]
Proposed changes work as expected in Merchant's live server.

**Pull request merged**
